eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://172.17.3.51:3306/springcloud?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9101
mybatis:
  mapper-locations: classpath*:/mybatis/*.xml
  type-aliases-package: atex.dev.spring.product.dto